rust_binary(
    name = "main",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    crate_root = "src/main.rs",
    deps = [
        "//third-party:libc", 
        "//cpp/manual_shims:ManualShimCppClass1", 
        "//cpp/manual_shims:ManualShimCppClass2",
        "//cpp/manual_shims:ManualShimIMax",
        "//cpp/manual_shims:ManualShimIMin",
        "//cpp/manual_shims:ManualShimIMinAndMax",
        "//cpp/manual_shims:ManualShimMinMaxFuncts",
    ],
)
