rust_binary(
    name = "main",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    crate_root = "src/main.rs",
    deps = [
        "//third-party:libc", 
        "//cpp:ManualShimCppClass1", 
        "//cpp:ManualShimCppClass2",
        "//cpp:ManualShimIMax",
        "//cpp:ManualShimIMin",
        "//cpp:ManualShimIMinAndMax",
        "//cpp:ManualShimMinMaxFuncts",
    ],
)
