rust_binary(
    name = "main",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    crate_root = "src/main.rs",
    deps = [
        "//third-party:libc",
    ],
)

# https://buck.build/rule/genrule.html
genrule(
  name = 'generate_cpp',
  srcs = [],
  bash = '$(exe //abigen:main) > $OUT',
  cmd_exe = '$(exe //abigen:main) > %OUT%',
  out = 'CppClass1.hpp',
)
